/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Yury Misiyuk (https://sketchfab.com/Tim0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/creepy-house-b6a4742bef3b4e9cb71de3fdf4f39a47
title: Creepy House
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'
import { useSpring, a } from '@react-spring/three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/house.gltf')
  const { actions } = useAnimations(animations, group)

  useFrame(() => {
    group.current.rotation.y += 0.01
  }, [])

  const animation = useSpring({
    scale: props.currentSection === 2 ? [0.03, 0.03, 0.03] : [0.04, 0.04, 0.04],
  })

  return (
    <a.group ref={group} {...props} dispose={null} scale={animation.scale}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-3840.98, 2407.3, -2314.42]}
            rotation={[-1.56, -0.09, 0.44]}
            scale={0.08}
          >
            <group position={[-6458.59, 1035.88, -23164.76]}>
              <mesh
                geometry={nodes['Cylinder014_Material_#28_0'].geometry}
                material={nodes['Cylinder014_Material_#28_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3840.98, 2407.3, -2314.42]}
            rotation={[-1.41, -0.03, 0.36]}
          >
            <group position={[-157.42, -274.06, -1900.76]}>
              <mesh
                geometry={nodes['Box026_Material_#2_0'].geometry}
                material={nodes['Box026_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3840.98, 2407.3, -2314.42]}
            rotation={[-Math.PI / 2, -0.09, Math.PI / 9]}
            scale={0.08}
          >
            <group position={[2891.48, 612.62, -24036.96]}>
              <mesh
                geometry={nodes['Cylinder015_Material_#28_0'].geometry}
                material={nodes['Cylinder015_Material_#28_0'].material}
              />
            </group>
          </group>
          <primitive object={nodes._rootJoint} />
          <group
            position={[-2559.03, 343.24, -3304.37]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1, 1, 1]}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box001_Material_#3_0'].geometry}
                material={nodes['Box001_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1058.92, 311.97, -3304.37]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[-1, -1, -1.12]}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box002_Material_#3_0'].geometry}
                material={nodes['Box002_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[410.69, 345.73, -3304.37]}
            rotation={[-Math.PI / 2, -0.09, Math.PI / 2]}
            scale={[1, 1, 1.04]}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box003_Material_#3_0'].geometry}
                material={nodes['Box003_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[1941.3, 356.69, -3304.37]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[-1, -1, -1.14]}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box004_Material_#3_0'].geometry}
                material={nodes['Box004_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[-310.68, 480.69, -3417.42]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={-1}
          >
            <group position={[0, -7.5, -2550]}>
              <mesh
                geometry={nodes['Box005_Material_#2_0'].geometry}
                material={nodes['Box005_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-349.37, 242.56, -3417.42]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={-1}
          >
            <group position={[0, 2.83, -2550]}>
              <mesh
                geometry={nodes['Box006_Material_#2_0'].geometry}
                material={nodes['Box006_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[2050.59, 344.73, -2884.27]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={-1}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box007_Material_#3_0'].geometry}
                material={nodes['Box007_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[2050.59, 368.15, -1384.16]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-1, -1, -1.05]}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box008_Material_#3_0'].geometry}
                material={nodes['Box008_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[2050.59, 300.91, 85.45]}
            rotation={[-1.66, 0, Math.PI]}
            scale={-1}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box009_Material_#3_0'].geometry}
                material={nodes['Box009_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[2050.59, 350, 1616.06]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={-1}
          >
            <group position={[0, 0, -350]}>
              <mesh
                geometry={nodes['Box010_Material_#3_0'].geometry}
                material={nodes['Box010_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[2163.64, 491.02, -635.92]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <group position={[0, 2.83, -2550]}>
              <mesh
                geometry={nodes['Box011_Material_#2_0'].geometry}
                material={nodes['Box011_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[2163.64, 239.62, -988.66]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <group position={[0, -0.11, -2197.26]}>
              <mesh
                geometry={nodes['Box012_Material_#2_0'].geometry}
                material={nodes['Box012_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-231.13, 1601.31, -974.1]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[-72.98, -79.72, -1601.31]}>
              <mesh
                geometry={nodes['Box013_Material_#19_0'].geometry}
                material={materials.Material_19}
              />
            </group>
          </group>
          <group
            position={[-314.03, 371.51, 1276.07]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.54, 0.54, 1]}
          >
            <group position={[0, 736.43, 140.33]}>
              <mesh
                geometry={nodes['Cylinder003_Material_#18_0'].geometry}
                material={nodes['Cylinder003_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 2465.43, 968.59]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -125]}>
              <mesh
                geometry={nodes['Box014_Material_#2_0'].geometry}
                material={nodes['Box014_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1973.17, 2462.31, -894.39]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          >
            <group position={[0, 0, -150]}>
              <mesh
                geometry={nodes['Box015_Material_#2_0'].geometry}
                material={nodes['Box015_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 2465.43, -2757.37]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          >
            <group position={[0, 0, -125]}>
              <mesh
                geometry={nodes['Box016_Material_#2_0'].geometry}
                material={nodes['Box016_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[1345.12, 2462.31, -894.39]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          >
            <group position={[0, 0, -150]}>
              <mesh
                geometry={nodes['Box017_Material_#2_0'].geometry}
                material={nodes['Box017_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1839.61, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[32.64, 0, -1839.61]}>
              <mesh
                geometry={nodes['Object001_Material_#2_0'].geometry}
                material={nodes['Object001_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1764.98, 943.74, -250.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, -9.54, -100]}>
              <mesh
                geometry={nodes['Box018_Material_#2_0'].geometry}
                material={nodes['Box018_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1764.98, 943.74, -1534.71]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group position={[0, -9.54, -100]}>
              <mesh
                geometry={nodes['Box019_Material_#2_0'].geometry}
                material={nodes['Box019_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[1136.92, 943.74, -250.86]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group position={[0, -9.54, -100]}>
              <mesh
                geometry={nodes['Box020_Material_#2_0'].geometry}
                material={nodes['Box020_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[1136.92, 943.74, -1534.71]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group position={[0, -9.54, -100]}>
              <mesh
                geometry={nodes['Box021_Material_#2_0'].geometry}
                material={nodes['Box021_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2080.79, 1723.34, -2312.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.74}
          >
            <group position={[0, 0, -13.8]}>
              <mesh
                geometry={nodes['Cylinder004_Material_#27_0'].geometry}
                material={nodes['Cylinder004_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2080.79, 1795.36, -2312.8]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={1.74}
          >
            <group position={[0, 0, -11]}>
              <mesh
                geometry={nodes['Tube001_Material_#27_0'].geometry}
                material={nodes['Tube001_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2080.79, 1481.9, -2312.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.74}
          >
            <group position={[0, 0, -125.33]}>
              <mesh
                geometry={nodes['Box022_Material_#27_0'].geometry}
                material={nodes['Box022_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1955.86, 1976.88, -2313.31]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          >
            <group position={[183.56, 0, -260.57]}>
              <mesh
                geometry={nodes['Cylinder005_Material_#27_0'].geometry}
                material={nodes['Cylinder005_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2081.92, 118.91, -1466.93]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -81.09]}>
              <mesh
                geometry={nodes['Box023_Material_#5_0'].geometry}
                material={nodes['Box023_Material_#5_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2081.92, 118.91, -348.75]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -81.09]}>
              <mesh
                geometry={nodes['Box024_Material_#5_0'].geometry}
                material={nodes['Box024_Material_#5_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2119.61, 285.68, -902.15]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -50]}>
              <mesh
                geometry={nodes['Box025_Material_#3_0'].geometry}
                material={nodes['Box025_Material_#3_0'].material}
              />
            </group>
          </group>
          <group
            position={[775.97, 425, 1480.13]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -425]}>
              <mesh
                geometry={nodes['Cylinder006_Material_#25_0'].geometry}
                material={nodes['Cylinder006_Material_#25_0'].material}
              />
            </group>
          </group>
          <group
            position={[1508.67, 271.53, 1747.21]}
            rotation={[-0.17, -0.44, Math.PI / 4]}
            scale={[0.95, 0.95, 0.95]}
          >
            <group position={[0, 0, -425]}>
              <mesh
                geometry={nodes['Cylinder007_Material_#25_0'].geometry}
                material={nodes['Cylinder007_Material_#25_0'].material}
              />
            </group>
          </group>
          <group
            position={[-149.79, 0, -770.81]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes['Cylinder008_Material_#29_0'].geometry}
              material={materials.Material_29}
            />
          </group>
          <group
            position={[-3189.82, 1229.22, -2548.32]}
            rotation={[-Math.PI / 2, 0, Math.PI / 9]}
          >
            <group position={[0, 0, -1247.74]}>
              <mesh
                geometry={nodes['Cylinder011_Material_#27_0'].geometry}
                material={nodes['Cylinder011_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3189.95, 742.08, -2554.28]}
            rotation={[0, Math.PI / 9, 0]}
          >
            <group position={[-1.91, 0, -400]}>
              <mesh
                geometry={nodes['Cylinder012_Material_#27_0'].geometry}
                material={nodes['Cylinder012_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4484.92, 1229.22, -2076.94]}
            rotation={[-Math.PI / 2, 0, Math.PI / 9]}
          >
            <group position={[0, 0, -1247.74]}>
              <mesh
                geometry={nodes['Cylinder009_Material_#27_0'].geometry}
                material={nodes['Cylinder009_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4485.06, 742.08, -2082.9]}
            rotation={[0, Math.PI / 9, 0]}
          >
            <group position={[-1.91, 0, -400]}>
              <mesh
                geometry={nodes['Cylinder010_Material_#27_0'].geometry}
                material={nodes['Cylinder010_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3840.98, 2407.3, -2314.42]}
            rotation={[Math.PI, 1.22, -Math.PI]}
          >
            <group position={[-2.39, 0, -694.85]}>
              <mesh
                geometry={nodes['Cylinder013_Material_#27_0'].geometry}
                material={nodes['Cylinder013_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1312.57, 725.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 1619.43, -1312.57]}>
              <mesh
                geometry={nodes['Object002_Material_#2_0'].geometry}
                material={nodes['Object002_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-76.26, 1245.67, 691.14]}
            rotation={[-0.02, 0, 0]}
            scale={1.34}
          >
            <group position={[0, 0, -17.5]}>
              <mesh
                geometry={nodes['Sphere001_Material_#27_0'].geometry}
                material={nodes['Sphere001_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[131.86, 4411.83, -784.47]}
            rotation={[-Math.PI / 2, -1.31, 0]}
          >
            <group position={[-987.61, 111.07, 1655.5]}>
              <mesh
                geometry={nodes['Plane001_Material_#26_0'].geometry}
                material={nodes['Plane001_Material_#26_0'].material}
              />
            </group>
          </group>
          <group position={[-314.03, 4647.2, -895.52]} rotation={[0, 0, 0]}>
            <group position={[0, -384.27, 1797.47]}>
              <mesh
                geometry={nodes['Plane002_Material_#24_0'].geometry}
                material={nodes['Plane002_Material_#24_0'].material}
              />
            </group>
          </group>
          <group position={[-311.66, 3754.94, 926.93]} rotation={[0, 0, 0]}>
            <group position={[0, 0, -24.98]}>
              <mesh
                geometry={nodes['Tube002_Material_#24_0'].geometry}
                material={nodes['Tube002_Material_#24_0'].material}
              />
            </group>
          </group>
          <group
            position={[-311.66, 3754.94, 902.28]}
            rotation={[0, 0, -Math.PI / 4]}
          >
            <group position={[0, 0, 5.74]}>
              <mesh
                geometry={nodes['Box027_Material_#2_0'].geometry}
                material={nodes['Box027_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-309.45, 4324.94, -2902.41]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          >
            <group position={[-2008.02, 0, -166.12]}>
              <mesh
                geometry={nodes['Box028_Material_#2_0'].geometry}
                material={nodes['Box028_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-309.45, 6753.33, 1275.72]}
            rotation={[1.11, 0, -Math.PI / 2]}
            scale={[-1, -1.06, -1.06]}
          >
            <group position={[-1979.48, 0, -150]}>
              <mesh
                geometry={nodes['Box029_Material_#2_0'].geometry}
                material={nodes['Box029_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-339.56, 5722.46, -926.77]}
            rotation={[-Math.PI / 2, -1.31, 0]}
          >
            <group position={[-2131.57, -31.22, 860.93]}>
              <mesh
                geometry={nodes['Shape001_Material_#26_0'].geometry}
                material={nodes['Shape001_Material_#26_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1828.28, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 0, -1828.28]}>
              <mesh
                geometry={nodes['Object_Material_#23_0'].geometry}
                material={nodes['Object_Material_#23_0'].material}
              />
            </group>
          </group>
          <group position={[-311.66, 3754.94, 908.02]} rotation={[0, 0, 0]}>
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane003_Material_#23_0'].geometry}
                material={nodes['Plane003_Material_#23_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3362.64, 75.44, -107.5]}
            rotation={[-0.04, -0.44, 0]}
            scale={[2.2, 2.2, 2.2]}
          >
            <group position={[-2.89, 1.39, -102.42]}>
              <mesh
                geometry={nodes['Cylinder016_Material_#33_0'].geometry}
                material={nodes['Cylinder016_Material_#33_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3377.26, 175.36, -26.7]}
            rotation={[-2.52, -0.68, -1.96]}
            scale={[2.2, 2.2, 2.2]}
          >
            <group position={[-2.89, 1.39, -102.42]}>
              <mesh
                geometry={nodes['Cylinder017_Material_#33_0'].geometry}
                material={nodes['Cylinder017_Material_#33_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3409.21, 157.83, -167.52]}
            rotation={[1.29, -0.99, 1.01]}
            scale={[1.83, 1.83, 1.83]}
          >
            <group position={[-2.89, 1.39, -102.42]}>
              <mesh
                geometry={nodes['Cylinder018_Material_#33_0'].geometry}
                material={nodes['Cylinder018_Material_#33_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3337.78, 33.68, -115.27]}
            rotation={[-1.61, 0, 0]}
            scale={1.09}
          >
            <mesh
              geometry={nodes['Plane004_Material_#32_0'].geometry}
              material={materials.Material_32}
            />
          </group>
          <group
            position={[-3084.55, 53.16, -194.7]}
            rotation={[-Math.PI / 2, 0, -0.87]}
            scale={[1.09, 1.09, 0.88]}
          >
            <group position={[2.34, 8.93, -3.61]}>
              <mesh
                geometry={nodes['GeoSphere001_Material_#18_0'].geometry}
                material={nodes['GeoSphere001_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3463.55, 65.64, -327.89]}
            rotation={[-Math.PI / 2, 0, -1.13]}
            scale={[1.09, 1.09, 0.88]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere002_Material_#18_0'].geometry}
                material={nodes['GeoSphere002_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3326.93, 49.97, -395.84]}
            rotation={[-Math.PI / 2, -0.17, -Math.PI / 4]}
            scale={[1.09, 1.09, 0.88]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere003_Material_#18_0'].geometry}
                material={nodes['GeoSphere003_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3161.33, 69.79, -346.29]}
            rotation={[-1.48, -0.06, 2.16]}
            scale={[2.35, 1.53, 1.91]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere004_Material_#18_0'].geometry}
                material={nodes['GeoSphere004_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3093.25, 65.8, 28.45]}
            rotation={[-1.32, -0.09, 2.37]}
            scale={[1.87, 1.87, 1.51]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere005_Material_#18_0'].geometry}
                material={nodes['GeoSphere005_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3624.04, 65.64, -194.49]}
            rotation={[-Math.PI / 2, 0, 0.73]}
            scale={[1.73, 2.2, 1.78]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere006_Material_#18_0'].geometry}
                material={nodes['GeoSphere006_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3232.71, 74.02, 194.05]}
            rotation={[-1.12, -0.28, 2.81]}
            scale={[1.09, 1.09, 0.88]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere007_Material_#18_0'].geometry}
                material={nodes['GeoSphere007_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3435.78, 63.01, 204.59]}
            rotation={[-1.42, 0.16, -0.19]}
            scale={[2.17, 2.17, 1.76]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere008_Material_#18_0'].geometry}
                material={nodes['GeoSphere008_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3597.31, 60.83, 18.77]}
            rotation={[-1.71, 0.15, -1.57]}
            scale={[1.16, 1.15, 0.88]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere009_Material_#18_0'].geometry}
                material={nodes['GeoSphere009_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[2163.64, 166.9, 1434.39]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={-1}
          >
            <group position={[0, -72.84, -4620.31]}>
              <mesh
                geometry={nodes['Object004_Material_#2_0'].geometry}
                material={nodes['Object004_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 383.75, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 0, -383.75]}>
              <mesh
                geometry={nodes['Object006_Material_#4_0'].geometry}
                material={nodes['Object006_Material_#4_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1600.1, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 0, -1600.1]}>
              <mesh
                geometry={nodes['Object008_Material_#2_0'].geometry}
                material={nodes['Object008_Material_#2_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 378.33, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 0, -378.33]}>
              <mesh
                geometry={nodes['Object010_Material_#4_0'].geometry}
                material={nodes['Object010_Material_#4_0'].material}
              />
              <mesh
                geometry={nodes['Object010_Material_#5_0'].geometry}
                material={nodes['Object010_Material_#5_0'].material}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1312.82, 677.98]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 1572.36, -1312.82]}>
              <mesh
                geometry={nodes['Object012_Material_#22_0'].geometry}
                material={materials.Material_22}
              />
            </group>
          </group>
          <group
            position={[-1667.86, 1602.25, -894.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[1191.79, 0, -1602.25]}>
              <mesh
                geometry={nodes['Object014_Material_#20_0'].geometry}
                material={materials.Material_20}
              />
            </group>
          </group>
          <group
            position={[-314.03, 1591.47, 773.7]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.14, 1, 1]}
          >
            <group position={[0, 1668.09, -1591.47]}>
              <mesh
                geometry={nodes['Object016_Material_#21_0'].geometry}
                material={materials.Material_21}
              />
            </group>
          </group>
          <group
            position={[-2080.79, 1509, -2312.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.74}
          >
            <group position={[0, 0, -140.95]}>
              <mesh
                geometry={nodes['Object018_Material_#23_0'].geometry}
                material={nodes['Object018_Material_#23_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2080.79, 1511.57, -2312.8]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.74}
          >
            <group position={[0, 0, -142.43]}>
              <mesh
                geometry={nodes['Shape002_Material_#27_0'].geometry}
                material={nodes['Shape002_Material_#27_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3148.02, 65.64, -120.6]}
            rotation={[-Math.PI / 2, 0, 2.88]}
            scale={[0.68, 0.68, 0.55]}
          >
            <group position={[-1.85, 0.8, -6.92]}>
              <mesh
                geometry={nodes['GeoSphere010_Material_#18_0'].geometry}
                material={nodes['GeoSphere010_Material_#18_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2557.39, 549.2, 2468.18]}
            rotation={[2.96, -1.13, 2.94]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane010_Material_#34_0'].geometry}
                material={nodes['Plane010_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2557.39, 549.2, 2468.18]}
            rotation={[3.11, -0.35, 3.05]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane011_Material_#34_0'].geometry}
                material={nodes['Plane011_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2557.39, 549.2, 2468.18]}
            rotation={[-3.1, 0.43, 3.05]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane012_Material_#34_0'].geometry}
                material={nodes['Plane012_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2557.39, 549.2, 2468.18]}
            rotation={[-2.91, 1.21, 2.89]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane013_Material_#34_0'].geometry}
                material={nodes['Plane013_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2022.63, 542.59, -4468.65]}
            rotation={[3.05, -1.13, -Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane014_Material_#34_0'].geometry}
                material={nodes['Plane014_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2022.63, 542.59, -4468.65]}
            rotation={[3.05, -Math.PI / 9, Math.PI]}
            scale={2.74}
          >
            <mesh
              geometry={nodes['Plane015_Material_#34_0'].geometry}
              material={nodes['Plane015_Material_#34_0'].material}
            />
          </group>
          <group
            position={[2022.63, 542.59, -4468.65]}
            rotation={[3.05, 0.44, -Math.PI]}
            scale={2.74}
          >
            <mesh
              geometry={nodes['Plane016_Material_#34_0'].geometry}
              material={nodes['Plane016_Material_#34_0'].material}
            />
          </group>
          <group
            position={[2022.63, 542.59, -4468.65]}
            rotation={[3.05, 1.22, Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane017_Material_#34_0'].geometry}
                material={nodes['Plane017_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3562.2, 573.17, -4044.07]}
            rotation={[2.78, -1.13, 2.94]}
            scale={3.17}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane018_Material_#34_0'].geometry}
                material={nodes['Plane018_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3562.2, 573.17, -4044.07]}
            rotation={[2.94, -0.35, 3.05]}
            scale={[3.17, 3.17, 3.17]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane019_Material_#34_0'].geometry}
                material={nodes['Plane019_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3562.2, 573.17, -4044.07]}
            rotation={[3.01, 0.43, 3.05]}
            scale={[3.17, 3.17, 3.17]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane020_Material_#34_0'].geometry}
                material={nodes['Plane020_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-3562.2, 573.17, -4044.07]}
            rotation={[-3.08, 1.21, 2.89]}
            scale={[3.17, 3.17, 3.17]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane021_Material_#34_0'].geometry}
                material={nodes['Plane021_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-1944.85, 549.2, -1640.48]}
            rotation={[0, -1.57, 0]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane022_Material_#34_0'].geometry}
                material={nodes['Plane022_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-861.61, 549.2, -2839.8]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane023_Material_#34_0'].geometry}
                material={nodes['Plane023_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-861.61, 549.2, -2839.8]}
            rotation={[Math.PI, -0.61, Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane024_Material_#34_0'].geometry}
                material={nodes['Plane024_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-861.61, 549.2, -2839.8]}
            rotation={[Math.PI, Math.PI / 6, -Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane025_Material_#34_0'].geometry}
                material={nodes['Plane025_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2566.25, 549.2, 2212.5]}
            rotation={[-2.79, -1.1, -2.75]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane026_Material_#34_0'].geometry}
                material={nodes['Plane026_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2566.25, 549.2, 2212.5]}
            rotation={[-3.08, -0.34, -2.96]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane027_Material_#34_0'].geometry}
                material={nodes['Plane027_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2566.25, 549.2, 2212.5]}
            rotation={[3.06, 0.43, -2.95]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane028_Material_#34_0'].geometry}
                material={nodes['Plane028_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2566.25, 549.2, 2212.5]}
            rotation={[2.7, 1.18, -2.67]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane029_Material_#34_0'].geometry}
                material={nodes['Plane029_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[4191.84, 549.2, -302.51]}
            rotation={[-2.79, -1.1, -2.75]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane030_Material_#34_0'].geometry}
                material={nodes['Plane030_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[4191.84, 549.2, -302.51]}
            rotation={[-3.08, -0.34, -2.96]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane031_Material_#34_0'].geometry}
                material={nodes['Plane031_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[4191.84, 549.2, -302.51]}
            rotation={[3.06, 0.43, -2.95]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane032_Material_#34_0'].geometry}
                material={nodes['Plane032_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[4191.84, 549.2, -302.51]}
            rotation={[2.7, 1.18, -2.67]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane033_Material_#34_0'].geometry}
                material={nodes['Plane033_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[1451.73, 549.2, 437.2]}
            rotation={[Math.PI, 1.48, -Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane034_Material_#34_0'].geometry}
                material={nodes['Plane034_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[1451.73, 549.2, 437.2]}
            rotation={[0, 0.44, 0]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane035_Material_#34_0'].geometry}
                material={nodes['Plane035_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[1451.73, 549.2, 437.2]}
            rotation={[Math.PI, 0.7, -Math.PI]}
            scale={2.74}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane036_Material_#34_0'].geometry}
                material={nodes['Plane036_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[749.19, 344.35, 2270.45]}
            rotation={[-3.01, 0.43, 3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane037_Material_#36_0'].geometry}
              material={nodes['Plane037_Material_#36_0'].material}
            />
          </group>
          <group
            position={[749.19, 344.35, 2270.45]}
            rotation={[-3.09, -0.36, 3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane038_Material_#36_0'].geometry}
              material={nodes['Plane038_Material_#36_0'].material}
            />
          </group>
          <group
            position={[749.19, 344.35, 2270.45]}
            rotation={[3.04, -1.13, 2.93]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane039_Material_#36_0'].geometry}
                material={nodes['Plane039_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[749.19, 344.35, 2270.45]}
            rotation={[0.32, -1.2, 0.24]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane040_Material_#36_0'].geometry}
                material={nodes['Plane040_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1619.27, 472.38, -492.15]}
            rotation={[Math.PI, 0.44, -Math.PI]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane041_Material_#36_0'].geometry}
                material={nodes['Plane041_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1619.27, 472.38, -492.15]}
            rotation={[Math.PI, -Math.PI / 9, Math.PI]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane042_Material_#36_0'].geometry}
                material={nodes['Plane042_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1619.27, 472.38, -492.15]}
            rotation={[Math.PI, -1.13, Math.PI]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane043_Material_#36_0'].geometry}
                material={nodes['Plane043_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1619.27, 472.38, -492.15]}
            rotation={[0, -1.22, 0]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane044_Material_#36_0'].geometry}
                material={nodes['Plane044_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2310.22, 461.2, 448.7]}
            rotation={[-3.01, 0.43, 3.05]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane045_Material_#36_0'].geometry}
                material={nodes['Plane045_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2310.22, 461.2, 448.7]}
            rotation={[-3.09, -0.36, 3.05]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane046_Material_#36_0'].geometry}
                material={nodes['Plane046_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2310.22, 461.2, 448.7]}
            rotation={[3.04, -1.13, 2.93]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane047_Material_#36_0'].geometry}
                material={nodes['Plane047_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2310.22, 461.2, 448.7]}
            rotation={[0.32, -1.2, 0.24]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane048_Material_#36_0'].geometry}
                material={nodes['Plane048_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2488.85, 461.2, -2103.48]}
            rotation={[-3.01, 0.43, 3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane049_Material_#36_0'].geometry}
              material={nodes['Plane049_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2488.85, 461.2, -2103.48]}
            rotation={[-3.09, -0.36, 3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane050_Material_#36_0'].geometry}
              material={nodes['Plane050_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2488.85, 461.2, -2103.48]}
            rotation={[3.04, -1.13, 2.93]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane051_Material_#36_0'].geometry}
              material={nodes['Plane051_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2488.85, 461.2, -2103.48]}
            rotation={[0.32, -1.2, 0.24]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane052_Material_#36_0'].geometry}
              material={nodes['Plane052_Material_#36_0'].material}
            />
          </group>
          <group
            position={[1746.45, 461.2, -2951.97]}
            rotation={[3.1, 0.44, -3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane053_Material_#36_0'].geometry}
              material={nodes['Plane053_Material_#36_0'].material}
            />
          </group>
          <group
            position={[1746.45, 461.2, -2951.97]}
            rotation={[-3.11, -0.34, -3.05]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane054_Material_#36_0'].geometry}
              material={nodes['Plane054_Material_#36_0'].material}
            />
          </group>
          <group
            position={[1746.45, 461.2, -2951.97]}
            rotation={[-2.96, -1.12, -2.94]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane055_Material_#36_0'].geometry}
              material={nodes['Plane055_Material_#36_0'].material}
            />
          </group>
          <group
            position={[1746.45, 461.2, -2951.97]}
            rotation={[-0.24, -1.22, -0.25]}
            scale={1.34}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane056_Material_#36_0'].geometry}
                material={nodes['Plane056_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4966.57, 369.79, -1519.54]}
            rotation={[-2.94, 0.4, 2.86]}
            scale={[1.66, 1.66, 1.66]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane057_Material_#36_0'].geometry}
                material={nodes['Plane057_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4966.57, 369.79, -1519.54]}
            rotation={[3.13, -0.36, 2.86]}
            scale={1.66}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane058_Material_#36_0'].geometry}
                material={nodes['Plane058_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4966.57, 369.79, -1519.54]}
            rotation={[2.7, -1.09, 2.55]}
            scale={1.66}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane059_Material_#36_0'].geometry}
                material={nodes['Plane059_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-4966.57, 369.79, -1519.54]}
            rotation={[0.67, -1.12, 0.63]}
            scale={[1.66, 1.66, 1.66]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane060_Material_#36_0'].geometry}
                material={nodes['Plane060_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[-2368.54, 332.83, -4040.4]}
            rotation={[3.13, 0.41, 2.95]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane061_Material_#36_0'].geometry}
              material={nodes['Plane061_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2368.54, 332.83, -4040.4]}
            rotation={[2.99, -0.36, 2.96]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane062_Material_#36_0'].geometry}
              material={nodes['Plane062_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2368.54, 332.83, -4040.4]}
            rotation={[2.69, -1.12, 2.74]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane063_Material_#36_0'].geometry}
              material={nodes['Plane063_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-2368.54, 332.83, -4040.4]}
            rotation={[0.34, -1.17, 0.46]}
            scale={1.34}
          >
            <mesh
              geometry={nodes['Plane064_Material_#36_0'].geometry}
              material={nodes['Plane064_Material_#36_0'].material}
            />
          </group>
          <group
            position={[-580.17, 76.35, -5841.02]}
            rotation={[2.88, -1.13, Math.PI]}
            scale={2.35}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane065_Material_#34_0'].geometry}
                material={nodes['Plane065_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-580.17, 76.35, -5841.02]}
            rotation={[2.88, -Math.PI / 9, Math.PI]}
            scale={[2.35, 2.35, 2.35]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane066_Material_#34_0'].geometry}
                material={nodes['Plane066_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-580.17, 76.35, -5841.02]}
            rotation={[2.88, 0.44, -Math.PI]}
            scale={2.35}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane067_Material_#34_0'].geometry}
                material={nodes['Plane067_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[-580.17, 76.35, -5841.02]}
            rotation={[2.88, 1.22, -Math.PI]}
            scale={[2.35, 2.35, 2.35]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane068_Material_#34_0'].geometry}
                material={nodes['Plane068_Material_#34_0'].material}
              />
            </group>
          </group>
          <group
            position={[2760.1, 336.38, -1159.53]}
            rotation={[3.12, 0.44, 3.1]}
            scale={[1.73, 1.05, 1.73]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane069_Material_#36_0'].geometry}
                material={nodes['Plane069_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[2760.1, 336.38, -1159.53]}
            rotation={[3.1, -0.34, 3.11]}
            scale={[1.73, 1.05, 1.73]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane070_Material_#36_0'].geometry}
                material={nodes['Plane070_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[2760.1, 336.38, -1159.53]}
            rotation={[3.04, -1.12, 3.06]}
            scale={[1.73, 1.05, 1.73]}
          >
            <mesh
              geometry={nodes['Plane071_Material_#36_0'].geometry}
              material={nodes['Plane071_Material_#36_0'].material}
            />
          </group>
          <group
            position={[2760.1, 336.38, -1159.53]}
            rotation={[0.06, -1.23, 0.1]}
            scale={[1.73, 1.05, 1.73]}
          >
            <mesh
              geometry={nodes['Plane072_Material_#36_0'].geometry}
              material={nodes['Plane072_Material_#36_0'].material}
            />
          </group>
          <group
            position={[1570.15, -39.74, 4398.95]}
            rotation={[-2.84, 0.43, 3.05]}
            scale={2.03}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane073_Material_#36_0'].geometry}
                material={nodes['Plane073_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1570.15, -39.74, 4398.95]}
            rotation={[-2.91, -0.36, 3.05]}
            scale={[2.03, 2.03, 2.03]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane074_Material_#36_0'].geometry}
                material={nodes['Plane074_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1570.15, -39.74, 4398.95]}
            rotation={[-3.07, -1.13, 2.93]}
            scale={[2.03, 2.03, 2.03]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane075_Material_#36_0'].geometry}
                material={nodes['Plane075_Material_#36_0'].material}
              />
            </group>
          </group>
          <group
            position={[1570.15, -39.74, 4398.95]}
            rotation={[0.49, -1.2, 0.24]}
            scale={[2.03, 2.03, 2.03]}
          >
            <group position={[0, 0, 0]}>
              <mesh
                geometry={nodes['Plane076_Material_#36_0'].geometry}
                material={nodes['Plane076_Material_#36_0'].material}
              />
            </group>
          </group>
          <skinnedMesh
            geometry={nodes['Cylinder019_Material_#31_0'].geometry}
            material={materials.Material_31}
            skeleton={nodes['Cylinder019_Material_#31_0'].skeleton}
          />
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/house.gltf')
