/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sprint (https://sketchfab.com/Sprintpt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bmw-700-minecraft-871232429f7740c88f90056783145c42
title: BMW 700 (Minecraft)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={[2, 2, 2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_0.geometry}
              material={nodes.mesh_0.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_1.geometry}
              material={nodes.mesh_1.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_2.geometry}
              material={nodes.mesh_2.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_3.geometry}
              material={nodes.mesh_3.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_4.geometry}
              material={nodes.mesh_4.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_5.geometry}
              material={nodes.mesh_5.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_6.geometry}
              material={nodes.mesh_6.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_7.geometry}
              material={nodes.mesh_7.material}
            />
          </group>
          <group
            position={[7.05, 6.8, 4.2]}
            rotation={[0, 0, -Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_8.geometry}
              material={nodes.mesh_8.material}
            />
          </group>
          <group
            position={[5.5, 6.8, 4.2]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_9.geometry}
              material={nodes.mesh_9.material}
            />
          </group>
          <group position={[8, 3.68, 3.75]}>
            <mesh
              geometry={nodes.mesh_10.geometry}
              material={nodes.mesh_10.material}
            />
          </group>
          <group position={[8, 3.68, 3.75]}>
            <mesh
              geometry={nodes.mesh_11.geometry}
              material={nodes.mesh_11.material}
            />
          </group>
          <group
            position={[8, 3.05, 6.15]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_12.geometry}
              material={nodes.mesh_12.material}
            />
          </group>
          <group position={[15.5, 15.5, 15.5]}>
            <mesh
              geometry={nodes.mesh_13.geometry}
              material={nodes.mesh_13.material}
            />
          </group>
          <group position={[15.5, 15.5, 15.5]}>
            <mesh
              geometry={nodes.mesh_14.geometry}
              material={nodes.mesh_14.material}
            />
          </group>
          <group position={[17.6, 15.5, 15.5]}>
            <mesh
              geometry={nodes.mesh_15.geometry}
              material={nodes.mesh_15.material}
            />
          </group>
          <group position={[17.6, 15.5, 15.5]}>
            <mesh
              geometry={nodes.mesh_16.geometry}
              material={nodes.mesh_16.material}
            />
          </group>
          <group position={[15.5, 15.5, 15.5]}>
            <mesh
              geometry={nodes.mesh_17.geometry}
              material={nodes.mesh_17.material}
            />
          </group>
          <group
            position={[8, 6.89, 2.56]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_18.geometry}
              material={nodes.mesh_18.material}
            />
          </group>
          <group position={[12, 6, 15]}>
            <mesh
              geometry={nodes.mesh_19.geometry}
              material={nodes.mesh_19.material}
            />
          </group>
          <group
            position={[12.45, 9.88, 13.92]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_20.geometry}
              material={nodes.mesh_20.material}
            />
          </group>
          <group
            position={[3.55, 9.88, 13.92]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_21.geometry}
              material={nodes.mesh_21.material}
            />
          </group>
          <group position={[8, 10.88, 5.68]}>
            <mesh
              geometry={nodes.mesh_22.geometry}
              material={nodes.mesh_22.material}
            />
          </group>
          <group position={[8, 10.88, 5.68]}>
            <mesh
              geometry={nodes.mesh_23.geometry}
              material={nodes.mesh_23.material}
            />
          </group>
          <group position={[8, 10.88, 5.68]}>
            <mesh
              geometry={nodes.mesh_24.geometry}
              material={nodes.mesh_24.material}
            />
          </group>
          <group position={[4, 6, 15]}>
            <mesh
              geometry={nodes.mesh_25.geometry}
              material={nodes.mesh_25.material}
            />
          </group>
          <group
            position={[8, 7.82, 4.15]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_26.geometry}
              material={nodes.mesh_26.material}
            />
          </group>
          <group
            position={[7.95, 9.09, 4.67]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_27.geometry}
              material={nodes.mesh_27.material}
            />
          </group>
          <group position={[8, 8, 5]}>
            <mesh
              geometry={nodes.mesh_28.geometry}
              material={nodes.mesh_28.material}
            />
          </group>
          <group position={[8, 10.88, 5.68]}>
            <mesh
              geometry={nodes.mesh_29.geometry}
              material={nodes.mesh_29.material}
            />
          </group>
          <group
            position={[8, 7.82, 4.15]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_30.geometry}
              material={nodes.mesh_30.material}
            />
          </group>
          <group
            position={[8.1, 7.79, 4.22]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_31.geometry}
              material={nodes.mesh_31.material}
            />
          </group>
          <group
            position={[7.9, 7.79, 4.22]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_32.geometry}
              material={nodes.mesh_32.material}
            />
          </group>
          <group
            position={[8.2, 10.13, 3.52]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_33.geometry}
              material={nodes.mesh_33.material}
            />
          </group>
          <group
            position={[8, 9.88, 4.96]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_34.geometry}
              material={nodes.mesh_34.material}
            />
          </group>
          <group
            position={[8, 9.1, 4.69]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_35.geometry}
              material={nodes.mesh_35.material}
            />
          </group>
          <group
            position={[8, 7.82, 4.05]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_36.geometry}
              material={nodes.mesh_36.material}
            />
          </group>
          <group
            position={[8, 7.82, 4.15]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_37.geometry}
              material={nodes.mesh_37.material}
            />
          </group>
          <group
            position={[8.05, 9.09, 4.67]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_38.geometry}
              material={nodes.mesh_38.material}
            />
          </group>
          <group position={[8, 8, 5]}>
            <mesh
              geometry={nodes.mesh_39.geometry}
              material={nodes.mesh_39.material}
            />
          </group>
          <group position={[8, 10.91, 5.68]}>
            <mesh
              geometry={nodes.mesh_40.geometry}
              material={nodes.mesh_40.material}
            />
          </group>
          <group
            position={[8, 7.31, 12.43]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_41.geometry}
              material={nodes.mesh_41.material}
            />
          </group>
          <group
            position={[8.3, 7.79, 11.73]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_42.geometry}
              material={nodes.mesh_42.material}
            />
          </group>
          <group
            position={[8.5, 7.79, 11.73]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_43.geometry}
              material={nodes.mesh_43.material}
            />
          </group>
          <group
            position={[8.6, 10.13, 12.44]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_44.geometry}
              material={nodes.mesh_44.material}
            />
          </group>
          <group
            position={[8, 7.31, 12.43]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_45.geometry}
              material={nodes.mesh_45.material}
            />
          </group>
          <group
            position={[8, 12.61, 9]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_46.geometry}
              material={nodes.mesh_46.material}
            />
          </group>
          <group
            position={[8, 11.22, 5.71]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_47.geometry}
              material={nodes.mesh_47.material}
            />
          </group>
          <group position={[8, 15.46, 15.29]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_48.geometry}
              material={nodes.mesh_48.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_49.geometry}
              material={nodes.mesh_49.material}
            />
            <mesh
              geometry={nodes.mesh_50.geometry}
              material={nodes.mesh_50.material}
            />
          </group>
          <group position={[8, 3.48, -5.42]}>
            <mesh
              geometry={nodes.mesh_51.geometry}
              material={nodes.mesh_51.material}
            />
          </group>
          <group position={[5.95, 7.25, 2.04]}>
            <mesh
              geometry={nodes.mesh_52.geometry}
              material={nodes.mesh_52.material}
            />
          </group>
          <group position={[6.05, 7.25, 2.04]}>
            <mesh
              geometry={nodes.mesh_53.geometry}
              material={nodes.mesh_53.material}
            />
          </group>
          <group
            position={[6.05, 7.25, 2.04]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_54.geometry}
              material={nodes.mesh_54.material}
            />
          </group>
          <group position={[5.95, 7.25, 2.04]}>
            <mesh
              geometry={nodes.mesh_55.geometry}
              material={nodes.mesh_55.material}
            />
          </group>
          <group position={[6.05, 7.25, 2.04]}>
            <mesh
              geometry={nodes.mesh_56.geometry}
              material={nodes.mesh_56.material}
            />
          </group>
          <group
            position={[6.05, 7.25, 2.04]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_57.geometry}
              material={nodes.mesh_57.material}
            />
          </group>
          <group position={[12.56, 6.98, 1.36]}>
            <mesh
              geometry={nodes.mesh_58.geometry}
              material={nodes.mesh_58.material}
            />
          </group>
          <group position={[12.56, 7.69, 2.06]}>
            <mesh
              geometry={nodes.mesh_59.geometry}
              material={nodes.mesh_59.material}
            />
          </group>
          <group position={[12.56, 7.1, 1.41]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_60.geometry}
              material={nodes.mesh_60.material}
            />
          </group>
          <group
            position={[12.25, 7.05, 0.5]}
            rotation={[0, Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_61.geometry}
              material={nodes.mesh_61.material}
            />
          </group>
          <group
            position={[12.99, 7.76, 1.98]}
            rotation={[0, -Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_62.geometry}
              material={nodes.mesh_62.material}
            />
          </group>
          <group
            position={[3.01, 7.76, 1.98]}
            rotation={[0, Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_63.geometry}
              material={nodes.mesh_63.material}
            />
          </group>
          <group position={[3.44, 7.69, 2.06]}>
            <mesh
              geometry={nodes.mesh_64.geometry}
              material={nodes.mesh_64.material}
            />
          </group>
          <group position={[3.44, 6.98, 1.36]}>
            <mesh
              geometry={nodes.mesh_65.geometry}
              material={nodes.mesh_65.material}
            />
          </group>
          <group position={[3.44, 7.1, 1.41]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_66.geometry}
              material={nodes.mesh_66.material}
            />
          </group>
          <group
            position={[3.75, 7.05, 0.5]}
            rotation={[0, -Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_67.geometry}
              material={nodes.mesh_67.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_68.geometry}
              material={nodes.mesh_68.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_69.geometry}
              material={nodes.mesh_69.material}
            />
          </group>
          <group position={[16, 16, 11]}>
            <mesh
              geometry={nodes.mesh_70.geometry}
              material={nodes.mesh_70.material}
            />
            <mesh
              geometry={nodes.mesh_71.geometry}
              material={nodes.mesh_71.material}
            />
          </group>
          <group position={[0, 16, 11]}>
            <mesh
              geometry={nodes.mesh_72.geometry}
              material={nodes.mesh_72.material}
            />
            <mesh
              geometry={nodes.mesh_73.geometry}
              material={nodes.mesh_73.material}
            />
          </group>
          <group position={[0.65, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_74.geometry}
              material={nodes.mesh_74.material}
            />
            <mesh
              geometry={nodes.mesh_75.geometry}
              material={nodes.mesh_75.material}
            />
          </group>
          <group position={[15.35, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_76.geometry}
              material={nodes.mesh_76.material}
            />
            <mesh
              geometry={nodes.mesh_77.geometry}
              material={nodes.mesh_77.material}
            />
          </group>
          <group
            position={[8.07, 4.2, -3.44]}
            rotation={[0, Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_78.geometry}
              material={nodes.mesh_78.material}
            />
            <mesh
              geometry={nodes.mesh_79.geometry}
              material={nodes.mesh_79.material}
            />
          </group>
          <group
            position={[7.93, 4.2, -3.44]}
            rotation={[0, -Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_80.geometry}
              material={nodes.mesh_80.material}
            />
            <mesh
              geometry={nodes.mesh_81.geometry}
              material={nodes.mesh_81.material}
            />
          </group>
          <group position={[8.32, 4.2, -5.27]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_82.geometry}
              material={nodes.mesh_82.material}
            />
            <mesh
              geometry={nodes.mesh_83.geometry}
              material={nodes.mesh_83.material}
            />
          </group>
          <group position={[7.68, 4.2, -5.27]} rotation={[0, Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_84.geometry}
              material={nodes.mesh_84.material}
            />
            <mesh
              geometry={nodes.mesh_85.geometry}
              material={nodes.mesh_85.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_86.geometry}
              material={nodes.mesh_86.material}
            />
            <mesh
              geometry={nodes.mesh_87.geometry}
              material={nodes.mesh_87.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_88.geometry}
              material={nodes.mesh_88.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_89.geometry}
              material={nodes.mesh_89.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_90.geometry}
              material={nodes.mesh_90.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_91.geometry}
              material={nodes.mesh_91.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_92.geometry}
              material={nodes.mesh_92.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_93.geometry}
              material={nodes.mesh_93.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_94.geometry}
              material={nodes.mesh_94.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_95.geometry}
              material={nodes.mesh_95.material}
            />
          </group>
          <group
            position={[5.95, 6.26, 8.23]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_96.geometry}
              material={nodes.mesh_96.material}
            />
            <mesh
              geometry={nodes.mesh_97.geometry}
              material={nodes.mesh_97.material}
            />
          </group>
          <group
            position={[5.95, 6.26, 8.23]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_98.geometry}
              material={nodes.mesh_98.material}
            />
            <mesh
              geometry={nodes.mesh_99.geometry}
              material={nodes.mesh_99.material}
            />
          </group>
          <group
            position={[5.95, 6.26, 8.23]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_100.geometry}
              material={nodes.mesh_100.material}
            />
            <mesh
              geometry={nodes.mesh_101.geometry}
              material={nodes.mesh_101.material}
            />
          </group>
          <group position={[8, 1, 6]}>
            <mesh
              geometry={nodes.mesh_102.geometry}
              material={nodes.mesh_102.material}
            />
            <mesh
              geometry={nodes.mesh_103.geometry}
              material={nodes.mesh_103.material}
            />
          </group>
          <group position={[8, 1, 6]}>
            <mesh
              geometry={nodes.mesh_104.geometry}
              material={nodes.mesh_104.material}
            />
            <mesh
              geometry={nodes.mesh_105.geometry}
              material={nodes.mesh_105.material}
            />
          </group>
          <group position={[8, 1, 6]}>
            <mesh
              geometry={nodes.mesh_106.geometry}
              material={nodes.mesh_106.material}
            />
            <mesh
              geometry={nodes.mesh_107.geometry}
              material={nodes.mesh_107.material}
            />
          </group>
          <group position={[8, 1, 6]}>
            <mesh
              geometry={nodes.mesh_108.geometry}
              material={nodes.mesh_108.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_109.geometry}
              material={nodes.mesh_109.material}
            />
            <mesh
              geometry={nodes.mesh_110.geometry}
              material={nodes.mesh_110.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_111.geometry}
              material={nodes.mesh_111.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_112.geometry}
              material={nodes.mesh_112.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_113.geometry}
              material={nodes.mesh_113.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_114.geometry}
              material={nodes.mesh_114.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_115.geometry}
              material={nodes.mesh_115.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_116.geometry}
              material={nodes.mesh_116.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_117.geometry}
              material={nodes.mesh_117.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_118.geometry}
              material={nodes.mesh_118.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_119.geometry}
              material={nodes.mesh_119.material}
            />
            <mesh
              geometry={nodes.mesh_120.geometry}
              material={nodes.mesh_120.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_121.geometry}
              material={nodes.mesh_121.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_122.geometry}
              material={nodes.mesh_122.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_123.geometry}
              material={nodes.mesh_123.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_124.geometry}
              material={nodes.mesh_124.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_125.geometry}
              material={nodes.mesh_125.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_126.geometry}
              material={nodes.mesh_126.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_127.geometry}
              material={nodes.mesh_127.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_128.geometry}
              material={nodes.mesh_128.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_129.geometry}
              material={nodes.mesh_129.material}
            />
            <mesh
              geometry={nodes.mesh_130.geometry}
              material={nodes.mesh_130.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_131.geometry}
              material={nodes.mesh_131.material}
            />
            <mesh
              geometry={nodes.mesh_132.geometry}
              material={nodes.mesh_132.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_133.geometry}
              material={nodes.mesh_133.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_134.geometry}
              material={nodes.mesh_134.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_135.geometry}
              material={nodes.mesh_135.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_136.geometry}
              material={nodes.mesh_136.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_137.geometry}
              material={nodes.mesh_137.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_138.geometry}
              material={nodes.mesh_138.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_139.geometry}
              material={nodes.mesh_139.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_140.geometry}
              material={nodes.mesh_140.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_141.geometry}
              material={nodes.mesh_141.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_142.geometry}
              material={nodes.mesh_142.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_143.geometry}
              material={nodes.mesh_143.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_144.geometry}
              material={nodes.mesh_144.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_145.geometry}
              material={nodes.mesh_145.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_146.geometry}
              material={nodes.mesh_146.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_147.geometry}
              material={nodes.mesh_147.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_148.geometry}
              material={nodes.mesh_148.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_149.geometry}
              material={nodes.mesh_149.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_150.geometry}
              material={nodes.mesh_150.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_151.geometry}
              material={nodes.mesh_151.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_152.geometry}
              material={nodes.mesh_152.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_153.geometry}
              material={nodes.mesh_153.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_154.geometry}
              material={nodes.mesh_154.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_155.geometry}
              material={nodes.mesh_155.material}
            />
            <mesh
              geometry={nodes.mesh_156.geometry}
              material={nodes.mesh_156.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_157.geometry}
              material={nodes.mesh_157.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_158.geometry}
              material={nodes.mesh_158.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_159.geometry}
              material={nodes.mesh_159.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_160.geometry}
              material={nodes.mesh_160.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_161.geometry}
              material={nodes.mesh_161.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_162.geometry}
              material={nodes.mesh_162.material}
            />
          </group>
          <group
            position={[8, 8, 8]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_163.geometry}
              material={nodes.mesh_163.material}
            />
          </group>
          <group position={[8, 8, 8]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_164.geometry}
              material={nodes.mesh_164.material}
            />
          </group>
          <group position={[8, 7.98, 8]}>
            <mesh
              geometry={nodes.mesh_165.geometry}
              material={nodes.mesh_165.material}
            />
          </group>
          <group position={[8, 7.98, 8]}>
            <mesh
              geometry={nodes.mesh_166.geometry}
              material={nodes.mesh_166.material}
            />
          </group>
          <group
            position={[12.55, 5.49, 20.97]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_167.geometry}
              material={nodes.mesh_167.material}
            />
          </group>
          <group
            position={[12.55, 5.49, 20.97]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_168.geometry}
              material={nodes.mesh_168.material}
            />
          </group>
          <group
            position={[8, 6.31, 16.46]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_169.geometry}
              material={nodes.mesh_169.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_170.geometry}
              material={nodes.mesh_170.material}
            />
          </group>
          <group position={[12.59, 6.46, 18.05]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_171.geometry}
              material={nodes.mesh_171.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_172.geometry}
              material={nodes.mesh_172.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_173.geometry}
              material={nodes.mesh_173.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_174.geometry}
              material={nodes.mesh_174.material}
            />
          </group>
          <group
            position={[8, 8.01, 7.92]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_175.geometry}
              material={nodes.mesh_175.material}
            />
          </group>
          <group position={[12.59, 6.45, 18.05]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_176.geometry}
              material={nodes.mesh_176.material}
            />
          </group>
          <group position={[7.98, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_177.geometry}
              material={nodes.mesh_177.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_178.geometry}
              material={nodes.mesh_178.material}
            />
          </group>
          <group position={[3.41, 6.45, 18.05]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_179.geometry}
              material={nodes.mesh_179.material}
            />
          </group>
          <group position={[3.41, 6.46, 18.05]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_180.geometry}
              material={nodes.mesh_180.material}
            />
          </group>
          <group position={[8.02, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_181.geometry}
              material={nodes.mesh_181.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_182.geometry}
              material={nodes.mesh_182.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_183.geometry}
              material={nodes.mesh_183.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_184.geometry}
              material={nodes.mesh_184.material}
            />
          </group>
          <group
            position={[8, 8.01, 7.92]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_185.geometry}
              material={nodes.mesh_185.material}
            />
          </group>
          <group
            position={[3.45, 5.49, 20.97]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_186.geometry}
              material={nodes.mesh_186.material}
            />
          </group>
          <group
            position={[3.45, 5.49, 20.97]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_187.geometry}
              material={nodes.mesh_187.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_188.geometry}
              material={nodes.mesh_188.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_189.geometry}
              material={nodes.mesh_189.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_190.geometry}
              material={materials.material_4}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_191.geometry}
              material={nodes.mesh_191.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_192.geometry}
              material={nodes.mesh_192.material}
            />
          </group>
          <group position={[15.35, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_193.geometry}
              material={nodes.mesh_193.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_194.geometry}
              material={nodes.mesh_194.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_195.geometry}
              material={nodes.mesh_195.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_196.geometry}
              material={nodes.mesh_196.material}
            />
          </group>
          <group position={[7.94, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_197.geometry}
              material={nodes.mesh_197.material}
            />
          </group>
          <group position={[8.06, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_198.geometry}
              material={nodes.mesh_198.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_199.geometry}
              material={nodes.mesh_199.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_200.geometry}
              material={nodes.mesh_200.material}
            />
          </group>
          <group position={[8.94, 10.46, 8]}>
            <mesh
              geometry={nodes.mesh_201.geometry}
              material={nodes.mesh_201.material}
            />
          </group>
          <group position={[7.06, 10.46, 8]}>
            <mesh
              geometry={nodes.mesh_202.geometry}
              material={nodes.mesh_202.material}
            />
          </group>
          <group
            position={[3.21, 2.14, 9.18]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_203.geometry}
              material={nodes.mesh_203.material}
            />
          </group>
          <group
            position={[12.79, 2.14, 9.18]}
            rotation={[0, 0, -Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_204.geometry}
              material={nodes.mesh_204.material}
            />
          </group>
          <group position={[7.94, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_205.geometry}
              material={nodes.mesh_205.material}
            />
          </group>
          <group position={[8.06, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_206.geometry}
              material={nodes.mesh_206.material}
            />
          </group>
          <group position={[7.94, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_207.geometry}
              material={nodes.mesh_207.material}
            />
          </group>
          <group position={[8.06, 4.41, 8]}>
            <mesh
              geometry={nodes.mesh_208.geometry}
              material={nodes.mesh_208.material}
            />
          </group>
          <group
            position={[3.21, 2.14, 9.18]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_209.geometry}
              material={nodes.mesh_209.material}
            />
          </group>
          <group
            position={[12.79, 2.14, 9.18]}
            rotation={[0, 0, -Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_210.geometry}
              material={nodes.mesh_210.material}
            />
          </group>
          <group position={[8.94, 10.46, 8]}>
            <mesh
              geometry={nodes.mesh_211.geometry}
              material={nodes.mesh_211.material}
            />
          </group>
          <group position={[7.06, 10.46, 8]}>
            <mesh
              geometry={nodes.mesh_212.geometry}
              material={nodes.mesh_212.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_213.geometry}
              material={nodes.mesh_213.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, -Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_214.geometry}
              material={nodes.mesh_214.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_215.geometry}
              material={nodes.mesh_215.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_216.geometry}
              material={nodes.mesh_216.material}
            />
          </group>
          <group position={[8, 7.95, 8]}>
            <mesh
              geometry={nodes.mesh_217.geometry}
              material={nodes.mesh_217.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_218.geometry}
              material={nodes.mesh_218.material}
            />
          </group>
          <group position={[8, 8, 8]}>
            <mesh
              geometry={nodes.mesh_219.geometry}
              material={nodes.mesh_219.material}
            />
          </group>
          <group position={[8, 7.95, 8]} rotation={[0, 0, Math.PI / 4]}>
            <mesh
              geometry={nodes.mesh_220.geometry}
              material={nodes.mesh_220.material}
            />
          </group>
          <group position={[15.55, 15, -0.5]}>
            <mesh
              geometry={nodes.mesh_221.geometry}
              material={nodes.mesh_221.material}
            />
          </group>
          <group position={[8, 2.13, 19.54]}>
            <mesh
              geometry={nodes.mesh_222.geometry}
              material={nodes.mesh_222.material}
            />
          </group>
          <group
            position={[8, 6.23, 16.45]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_223.geometry}
              material={nodes.mesh_223.material}
            />
          </group>
          <group
            position={[7.75, 6.23, 16.45]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_224.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.mesh_225.geometry}
              material={nodes.mesh_225.material}
            />
          </group>
          <group
            position={[8, 6.27, 16.45]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_226.geometry}
              material={nodes.mesh_226.material}
            />
          </group>
          <group
            position={[8, 6.31, 16.46]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_227.geometry}
              material={nodes.mesh_227.material}
            />
          </group>
          <group
            position={[8, 6.23, 16.45]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_228.geometry}
              material={nodes.mesh_228.material}
            />
          </group>
          <group
            position={[7.05, 6.22, 20.34]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_229.geometry}
              material={nodes.mesh_229.material}
            />
          </group>
          <group
            position={[8, 6.22, 20.34]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_230.geometry}
              material={nodes.mesh_230.material}
            />
          </group>
          <group position={[7.04, 3.02, 18.07]} rotation={[0, Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_231.geometry}
              material={nodes.mesh_231.material}
            />
          </group>
          <group position={[8.96, 3.02, 18.07]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_232.geometry}
              material={nodes.mesh_232.material}
            />
          </group>
          <group position={[8, 3.47, 21.39]}>
            <mesh
              geometry={nodes.mesh_233.geometry}
              material={nodes.mesh_233.material}
            />
          </group>
          <group position={[8, 3.47, 21.39]}>
            <mesh
              geometry={nodes.mesh_234.geometry}
              material={nodes.mesh_234.material}
            />
          </group>
          <group
            position={[5.6, 4.67, 20.88]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_235.geometry}
              material={nodes.mesh_235.material}
            />
            <mesh
              geometry={nodes.mesh_236.geometry}
              material={nodes.mesh_236.material}
            />
          </group>
          <group position={[8.05, 3.48, -5.42]}>
            <mesh
              geometry={nodes.mesh_237.geometry}
              material={nodes.mesh_237.material}
            />
            <mesh
              geometry={nodes.mesh_238.geometry}
              material={nodes.mesh_238.material}
            />
          </group>
          <group position={[8, 3.48, -5.42]}>
            <mesh
              geometry={nodes.mesh_239.geometry}
              material={nodes.mesh_239.material}
            />
          </group>
          <group
            position={[9.99, 4.18, -4.62]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_240.geometry}
              material={nodes.mesh_240.material}
            />
          </group>
          <group
            position={[6.01, 4.18, -4.62]}
            rotation={[0, 0, -Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_241.geometry}
              material={nodes.mesh_241.material}
            />
          </group>
          <group position={[8, 3.48, -5.42]}>
            <mesh
              geometry={nodes.mesh_242.geometry}
              material={nodes.mesh_242.material}
            />
          </group>
          <group
            position={[10.12, 3.23, -1.22]}
            rotation={[0, -Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_243.geometry}
              material={nodes.mesh_243.material}
            />
          </group>
          <group
            position={[5.88, 3.23, -1.22]}
            rotation={[0, Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_244.geometry}
              material={nodes.mesh_244.material}
            />
          </group>
          <group position={[8.83, 3.23, -2.42]} rotation={[0, Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_245.geometry}
              material={nodes.mesh_245.material}
            />
          </group>
          <group position={[7.17, 3.23, -2.42]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_246.geometry}
              material={nodes.mesh_246.material}
            />
          </group>
          <group position={[8, 3.48, -5.42]}>
            <mesh
              geometry={nodes.mesh_247.geometry}
              material={nodes.mesh_247.material}
            />
          </group>
          <group
            position={[8.05, 4.14, -3.42]}
            rotation={[0, Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_248.geometry}
              material={nodes.mesh_248.material}
            />
          </group>
          <group position={[8.29, 4.14, -5.25]} rotation={[0, -Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_249.geometry}
              material={nodes.mesh_249.material}
            />
          </group>
          <group position={[8, 3.74, -5.38]}>
            <mesh
              geometry={nodes.mesh_250.geometry}
              material={nodes.mesh_250.material}
            />
          </group>
          <group
            position={[8, 4.43, -5.8]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_251.geometry}
              material={nodes.mesh_251.material}
            />
          </group>
          <group position={[8, 4.92, -6.01]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh
              geometry={nodes.mesh_252.geometry}
              material={nodes.mesh_252.material}
            />
          </group>
          <group
            position={[8, 6.35, -3.77]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_253.geometry}
              material={nodes.mesh_253.material}
            />
          </group>
          <group position={[8, 8, 5]}>
            <mesh
              geometry={nodes.mesh_254.geometry}
              material={nodes.mesh_254.material}
            />
          </group>
          <group position={[8, 8, 5]}>
            <mesh
              geometry={nodes.mesh_255.geometry}
              material={nodes.mesh_255.material}
            />
          </group>
          <group
            position={[8.6, 10.13, 12.44]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_256.geometry}
              material={nodes.mesh_256.material}
            />
          </group>
          <group
            position={[8.2, 10.13, 3.52]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_257.geometry}
              material={nodes.mesh_257.material}
            />
          </group>
          <group
            position={[8.4, 9.88, 11]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_258.geometry}
              material={nodes.mesh_258.material}
            />
          </group>
          <group position={[15.35, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_259.geometry}
              material={nodes.mesh_259.material}
            />
          </group>
          <group position={[0.65, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_260.geometry}
              material={nodes.mesh_260.material}
            />
          </group>
          <group
            position={[8, 6.87, 2.5]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_261.geometry}
              material={nodes.mesh_261.material}
            />
          </group>
          <group
            position={[8, 9.66, 5.72]}
            rotation={[Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_262.geometry}
              material={nodes.mesh_262.material}
            />
          </group>
          <group
            position={[8, 5.66, -6.4]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_263.geometry}
              material={nodes.mesh_263.material}
            />
          </group>
          <group
            position={[8, 5.66, -6.4]}
            rotation={[-Math.PI / 8, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_264.geometry}
              material={nodes.mesh_264.material}
            />
          </group>
          <group position={[0.45, 15, 16.5]}>
            <mesh
              geometry={nodes.mesh_265.geometry}
              material={nodes.mesh_265.material}
            />
          </group>
          <group position={[15.55, 15, 16.5]}>
            <mesh
              geometry={nodes.mesh_266.geometry}
              material={nodes.mesh_266.material}
            />
          </group>
          <group position={[15.55, 15, 16.5]}>
            <mesh
              geometry={nodes.mesh_267.geometry}
              material={nodes.mesh_267.material}
            />
          </group>
          <group position={[15.35, 16.34, 11]}>
            <mesh
              geometry={nodes.mesh_268.geometry}
              material={nodes.mesh_268.material}
            />
          </group>
          <group position={[7.7, 4.14, -5.25]} rotation={[0, Math.PI / 4, 0]}>
            <mesh
              geometry={nodes.mesh_269.geometry}
              material={nodes.mesh_269.material}
            />
          </group>
          <group
            position={[7.95, 4.14, -3.42]}
            rotation={[0, -Math.PI / 8, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_270.geometry}
              material={nodes.mesh_270.material}
            />
          </group>
          <group position={[0.65, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_271.geometry}
              material={nodes.mesh_271.material}
            />
          </group>
          <group position={[0.65, 16.34, 11]}>
            <mesh
              geometry={nodes.mesh_272.geometry}
              material={nodes.mesh_272.material}
            />
          </group>
          <group position={[0.65, 16.5, 11]}>
            <mesh
              geometry={nodes.mesh_273.geometry}
              material={nodes.mesh_273.material}
            />
          </group>
          <group
            position={[4, -0.19, 7.75]}
            rotation={[0, 0, Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_274.geometry}
              material={nodes.mesh_274.material}
            />
          </group>
          <group
            position={[12, -0.19, 7.75]}
            rotation={[0, 0, -Math.PI / 8]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.mesh_275.geometry}
              material={nodes.mesh_275.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
