/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ishaknapitupulucxr2 (https://sketchfab.com/ishaknapitupulucxr2)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lamborghini-huracan-performante-dd482c3f5378434787950b826c349b80
title: Lamborghini Huracan Performante
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'
import { useSpring, a } from '@react-spring/three'

export default function Model({ currentSection }) {
  const modelRef = useRef()
  const modelRef2 = useRef()
  const modelRef3 = useRef()
  const modelRef4 = useRef()
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/car.gltf')
  const { actions } = useAnimations(animations, group)
  const [scale, setScale] = useState([])
  const [isRotation, setIsRotation] = useState(false)

  useFrame(() => {
    if (isRotation) {
      modelRef.current.rotation.x += 0.05
      modelRef2.current.rotation.x += 0.05
      modelRef3.current.rotation.x += 0.05
      modelRef4.current.rotation.x += 0.05
    }
  }, [isRotation])

  useEffect(() => {
    if (currentSection === 0) {
      setScale([2, 2, 2])
      setIsRotation(true)
    } else if (currentSection === 1) {
      setScale([1.3, 1.3, 1.3])
      setIsRotation(false)
      // group.current.rotation.y = 0
      // group.current.rotation.z = 0
    } else {
      // group.current.rotation.y = -0.5
      // group.current.rotation.z = 0.1
    }
  }, [currentSection])

  const animation = useSpring({
    rotation: currentSection === 2 ? [0, -0.5, 0.3] : [0, -0.5, 0.1],
    scale: currentSection === 0 ? [2, 2, 2] : [1.3, 1.3, 1.3],
  })

  return (
    <a.group
      ref={group}
      dispose={null}
      scale={animation.scale}
      rotation={animation.rotation}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[88.69, 64.34, 85.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017004_EXT_Carpaint002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017004_EXT_Carpaint002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017027_EXT_Damage_glass002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017027_EXT_Damage_glass002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017058_EXT_Plastic002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017058_EXT_Plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017059_EXT_Damage_glass002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017059_EXT_Damage_glass002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017061_EXT_Carpaint002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017061_EXT_Carpaint002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017062_INT_fabric_black002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017062_INT_fabric_black002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017069_INT_plastic_black002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017069_INT_plastic_black002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017070_INT_plastic_blacksniny002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017070_INT_plastic_blacksniny002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017074_INT_Y002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017074_INT_Y002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017076_INT_grid1002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017076_INT_grid1002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017078_CarbonForgedComposite_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017078_CarbonForgedComposite_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017080_INT_detail_chrome002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017080_INT_detail_chrome002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017081_INT_detail_plastic002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017081_INT_detail_plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017082_INT_detail_text002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017082_INT_detail_text002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017083_INT_detail_chrome002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017083_INT_detail_chrome002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017084_INT_cuciture002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017084_INT_cuciture002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017085_EXT_Plastic002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017085_EXT_Plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017087_EXT_MIRROR002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017087_EXT_MIRROR002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017089_EXT_Stripe002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017089_EXT_Stripe002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017092_INT_grid1002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017092_INT_grid1002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017093_INT_detail_text002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017093_INT_detail_text002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_metal002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_metal002_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_plastic002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_plastic002_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_text002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017096_INT_detail_text002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017095_EXT_Logo_Perf002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017095_EXT_Logo_Perf002_0
                    .material
                }
              />
            </group>
            <group
              position={[-0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017103_INT_detail_metal002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017103_INT_detail_metal002_0
                    .material
                }
              />
            </group>
          </group>
          <group
            position={[-88.69, 64.34, 85.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017014_EXT_Carpaint002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017014_EXT_Carpaint002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017003_EXT_Carpaint002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017003_EXT_Carpaint002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017056_EXT_Damage_glass002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017056_EXT_Damage_glass002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017057_EXT_Plastic002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017057_EXT_Plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017060_EXT_Damage_glass002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017060_EXT_Damage_glass002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017063_INT_fabric_black002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017063_INT_fabric_black002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017072_INT_plastic_blacksniny002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017072_INT_plastic_blacksniny002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017075_INT_Y002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017075_INT_Y002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017077_INT_grid1002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017077_INT_grid1002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017086_EXT_Plastic002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017086_EXT_Plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017088_EXT_MIRROR002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017088_EXT_MIRROR002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017090_EXT_Stripe002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017090_EXT_Stripe002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes.Lamborghini_Huracan_Performante_2017091_INT_grid1002_0
                    .geometry
                }
                material={
                  nodes.Lamborghini_Huracan_Performante_2017091_INT_grid1002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017094_INT_detail_text002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017094_INT_detail_text002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017097_EXT_Logo_Perf002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017097_EXT_Logo_Perf002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017098_INT_plastic_black002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017098_INT_plastic_black002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017099_INT_cuciture002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017099_INT_cuciture002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017100_INT_detail_plastic002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017100_INT_detail_plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017101_CarbonForgedComposite_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017101_CarbonForgedComposite_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017102_INT_detail_chrome002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017102_INT_detail_chrome002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_text002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_text002_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_metal002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_metal002_0
                    .material
                }
              />
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_plastic002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017104_INT_detail_plastic002_0
                    .material
                }
              />
            </group>
            <group
              position={[0.89, 0.85, -0.66]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes
                    .Lamborghini_Huracan_Performante_2017105_INT_detail_metal002_0
                    .geometry
                }
                material={
                  nodes
                    .Lamborghini_Huracan_Performante_2017105_INT_detail_metal002_0
                    .material
                }
              />
            </group>
          </group>
          <group
            position={[83.36, 32.94, 131.06]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            ref={modelRef}
          >
            <mesh
              geometry={nodes.WheelFtL_EXT_WHEEL001_0.geometry}
              material={nodes.WheelFtL_EXT_WHEEL001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtL_EXT_RIM001_0.geometry}
              material={nodes.WheelFtL_EXT_RIM001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtL_EXT_Detail001_0.geometry}
              material={nodes.WheelFtL_EXT_Detail001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtL_EXT_BRAKEDISC001_0.geometry}
              material={nodes.WheelFtL_EXT_BRAKEDISC001_0.material}
            />
          </group>
          <group
            position={[83.36, 32.94, 131.06]}
            rotation={[0, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.WheelbrakeFtL_EXT_Caliper001_0.geometry}
              material={nodes.WheelbrakeFtL_EXT_Caliper001_0.material}
            />
          </group>
          <group
            position={[81.39, 34.11, -131.11]}
            rotation={[0, 0, 0]}
            scale={[113.53, 100, 100]}
          >
            <mesh
              geometry={nodes.WheelbrakeBkL_EXT_Caliper001_0.geometry}
              material={nodes.WheelbrakeBkL_EXT_Caliper001_0.material}
            />
          </group>
          <group
            position={[-83.36, 32.94, 131.06]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
            ref={modelRef2}
          >
            <mesh
              geometry={nodes.WheelFtR_EXT_WHEEL001_0.geometry}
              material={nodes.WheelFtR_EXT_WHEEL001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtR_EXT_RIM001_0.geometry}
              material={nodes.WheelFtR_EXT_RIM001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtR_EXT_Detail001_0.geometry}
              material={nodes.WheelFtR_EXT_Detail001_0.material}
            />
            <mesh
              geometry={nodes.WheelFtR_EXT_BRAKEDISC001_0.geometry}
              material={nodes.WheelFtR_EXT_BRAKEDISC001_0.material}
            />
          </group>
          <group
            position={[-83.36, 32.94, 131.06]}
            rotation={[-0.24, 0, -Math.PI]}
            scale={100}
          >
            <mesh
              geometry={nodes.WheelbrakeFtR_EXT_Caliper001_0.geometry}
              material={nodes.WheelbrakeFtR_EXT_Caliper001_0.material}
            />
          </group>
          <group
            position={[81.39, 34.11, -131.11]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[120.4, 106.05, 106.05]}
            ref={modelRef3}
          >
            <mesh
              geometry={nodes.WheelBkL_EXT_WHEEL001_0.geometry}
              material={nodes.WheelBkL_EXT_WHEEL001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkL_EXT_RIM001_0.geometry}
              material={nodes.WheelBkL_EXT_RIM001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkL_EXT_Detail001_0.geometry}
              material={nodes.WheelBkL_EXT_Detail001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkL_EXT_BRAKEDISC001_0.geometry}
              material={nodes.WheelBkL_EXT_BRAKEDISC001_0.material}
            />
          </group>
          <group
            position={[-81.39, 34.11, -131.11]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[113.53, 100, 100]}
          >
            <mesh
              geometry={nodes.WheelbrakeBkR_EXT_Caliper001_0.geometry}
              material={nodes.WheelbrakeBkR_EXT_Caliper001_0.material}
            />
          </group>
          <group
            position={[-81.39, 34.11, -131.11]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[120.4, 106.05, 106.05]}
            ref={modelRef4}
          >
            <mesh
              geometry={nodes.WheelBkR_EXT_WHEEL001_0.geometry}
              material={nodes.WheelBkR_EXT_WHEEL001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkR_EXT_RIM001_0.geometry}
              material={nodes.WheelBkR_EXT_RIM001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkR_EXT_Detail001_0.geometry}
              material={nodes.WheelBkR_EXT_Detail001_0.material}
            />
            <mesh
              geometry={nodes.WheelBkR_EXT_BRAKEDISC001_0.geometry}
              material={nodes.WheelBkR_EXT_BRAKEDISC001_0.material}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017079_INT_Windows_Black002_0
                  .geometry
              }
              material={materials['INT_Windows_Black.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017001_INT_cuciture002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017001_INT_cuciture002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017002_INT_fabric_black002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017002_INT_fabric_black002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017005_INT_leather_black002_0
                  .geometry
              }
              material={materials['INT_leather_black.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017006_INT_plastic_black002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017006_INT_plastic_black002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017007_INT_plastic_blacksniny002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017007_INT_plastic_blacksniny002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017008_INT_detail_plastic002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017008_INT_detail_plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017009_INT_detail_text002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017009_INT_detail_text002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017010_CarbonForgedComposite_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017010_CarbonForgedComposite_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017011_INT_DISPLAY_AT002_0
                  .geometry
              }
              material={materials['INT_DISPLAY_AT.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017012_INT_DISPLAY002_0
                  .geometry
              }
              material={materials['INT_DISPLAY.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017013_INT_grid1002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017013_INT_grid1002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017015_INT_Y002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017015_INT_Y002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017016_INT_detail_chrome002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017016_INT_detail_chrome002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017017_INT_detail_metal002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017017_INT_detail_metal002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017018_EXT_Plastic002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017018_EXT_Plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017019_INT_metal_black002_0
                  .geometry
              }
              material={materials['INT_metal_black.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017020_INT_metal_chrome002_0
                  .geometry
              }
              material={materials['INT_metal_chrome.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017021_INT_metal_red002_0
                  .geometry
              }
              material={materials['INT_metal_red.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017022_INT_plastic_red002_0
                  .geometry
              }
              material={materials['INT_plastic_red.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017023_EXT_MIRROR002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017023_EXT_MIRROR002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017024_Metal_0.geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017024_Metal_0.material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017025_INT_detail_logo002_0
                  .geometry
              }
              material={materials['INT_detail_logo.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017028_EXT_MIRROR002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017028_EXT_MIRROR002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017029_INT_cinture_cinture002_0
                  .geometry
              }
              material={materials['INT_cinture_cinture.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017033_EXT_MECHANICS_Rubber002_0
                  .geometry
              }
              material={materials['EXT_MECHANICS_Rubber.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017034_Black_0.geometry
              }
              material={materials.Black}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017035_EXT_Detail001_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017035_EXT_Detail001_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017036_EXT_Plastic002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017036_EXT_Plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017038_EXT_Carpaint002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017038_EXT_Carpaint002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017039_EXT_Mechanics_comp002_0
                  .geometry
              }
              material={materials['EXT_Mechanics_comp.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017040_EXT_Plastic002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017040_EXT_Plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017041_EXT_Plastic002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017041_EXT_Plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017042_CarbonForgedComposite_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017042_CarbonForgedComposite_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017043_Metal_0.geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017043_Metal_0.material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017044_EXT_MECHANICS_METAL002_0
                  .geometry
              }
              material={materials['EXT_MECHANICS_METAL.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017045_EXT_Grid_metal002_0
                  .geometry
              }
              material={materials['EXT_Grid_metal.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017046_EXT_LOGOS_BRUSHED_METAL002_0
                  .geometry
              }
              material={materials['EXT_LOGOS_BRUSHED_METAL.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017047_EXT_Plastic002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017047_EXT_Plastic002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017064_CarbonForgedComposite_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017064_CarbonForgedComposite_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017065_EXT_MECHANICS_Plastic002_0
                  .geometry
              }
              material={materials['EXT_MECHANICS_Plastic.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017066_EXT_PLATE002_0
                  .geometry
              }
              material={materials['EXT_PLATE.002']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017067_EmissiVeTlL_0
                  .geometry
              }
              material={materials.EmissiVeTlL}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017068_EmissiveFtL_0
                  .geometry
              }
              material={materials.EmissiveFtL}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017073_EXT_Damage_glass002_0
                  .geometry
              }
              material={
                nodes
                  .Lamborghini_Huracan_Performante_2017073_EXT_Damage_glass002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017030_EXT_MIRROR002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017030_EXT_MIRROR002_0
                  .material
              }
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes
                  .Lamborghini_Huracan_Performante_2017032_EXT_REAR_Light003_0
                  .geometry
              }
              material={materials['EXT_REAR_Light.003']}
            />
          </group>
          <group position={[0, -1.75, 0]} rotation={[0, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Lamborghini_Huracan_Performante_2017026_EXT_Stripe002_0
                  .geometry
              }
              material={
                nodes.Lamborghini_Huracan_Performante_2017026_EXT_Stripe002_0
                  .material
              }
            />
          </group>
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/car.gltf')
